spring.application.name=demo

# 1. The address to your specific database
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing_db

# 2. Database credentials (username is usually 'postgres' by default)
spring.datasource.username=postgres
spring.datasource.password=1234

# 3. Tell Hibernate to automatically build the SQL tables based on our Java Classes!
spring.jpa.hibernate.ddl-auto=update

# 4. Show the SQL commands in the console so we can see the magic happen
spring.jpa.show-sql=true

# 5. Route configuration for Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
